parser: babel-eslint

extends:
  - airbnb
  - prettier
  - prettier/react

env:
  browser: true
  jest: true
  node: true

rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
        - ".js"
        - ".jsx"
